### ISSUE TITLE
[6주차] 프로토콜이란 무엇인지 설명하시오.

### ISSUE THREAD

**Issue by kangddong** [LetsSwifty/iOS_Interview#6]

**Comment by obtusa07** [comment]
# Swift 문서에서의 protocol 정의
프로토콜 (protocol) 은 메서드, 프로퍼티, 그리고 특정 작업이나 기능의 부분이 적합한 다른 요구사항의 청사진을 정의합니다. 프로토콜은 요구사항의 구현을 제공하기 위해 클래스, 구조체, 또는 열거형에 의해 채택될 수 있습니다. 프로토콜의 요구사항에 충족하는 모든 타입은 프로토콜에 준수 (conform) 한다고 합니다.

프로토콜이 매우 강력한 기능이기 때문에 protocol oriented programming 이라는 방법론이 존재한다.

## 예시

```
protocol Toggling {
    mutating func toggle()
}

```

위와 같은 Toggling 프로토콜을 선언하고 이를 준수하는 타입을 만들려고 한다면 항상 toggle이라는 메서드를 구현해야 한다.

- 타입 선언, 메서드 선언 또는 변수 선언에서 프로토콜을 사용할 수 있다. 
- 기술적으로 프로토콜을 객체 또는 구조의 인터페이스로 사용하는 것은 가능하지만, Swift에서는 일반적으로 그렇게 사용되지 않는다. 

## 사용 방법

### Top level에서 선언

```
enum State: Int, Toggling {
    case off = 0
    case on
    
    mutating func toggle() {
        self = self == .on ? .off : .on
    }
}

var state: State = .on
state.toggle()
assert(state == .off)

```

상기 코드는 top level에서 프로토콜을 선언하는 방법을 보여준다. 이 때 raw value 선언을 먼저 해주고 프로토콜은 그 다음에 선언해준다.


### extension에서 선언

```
internal extension Bool: Toggling {
    mutating func toggle() {
        self = !self
    }
}

var isReady = false
isReady.toggle()
assert(isReady)
```

위 방식은 두가지 방면에서 장점이 존재한다.

1. 기존 코드에 수정을 하지 않고 붙여 씀으로서 기존 유형에 기능을 붙이는 것이 가능하다
2. 접근 수준을 제어하여 원하는 범위에만 한정되어 코드를 작성할 수 있다.

### 프로토콜에서 extension의 이점 하나 더

```
protocol Toggling {
    mutating func toggle()
    var isActive: Bool { get }
}

extension Toggling where Self == Bool {
    var isActive: Bool {
        return self
    }
}

extension Toggling where Self == State {
    var isActive: Bool {
        return self == .on
    }
}

```

상기 코드에서 isActive라는 변수가 존재하는데 타입 안에서 구현을 하지 않아도 이를 자동으로 초기화 할 수 있다.








ref
---
https://bbiguduk.gitbook.io/swift/language-guide-1/protocols

**Comment by kangddong** [comment]
프로토콜은 하나의 타입으로  class, struct, enum에 특정 작업 또는 일부 기능에 적합한 메서드, 속성 및 행동을 정의한 것입니다.
class, struct, enum에서 protocol를 채택할 수 있으며, 프로토콜의 요구 사항을 충족하는 모든 유형은 해당 프로토콜을 준수한다고 합니다.

요구 사항 지정하는 것 외에도 프로토콜을 확장하여 이러한 요구 사항의 일부를 구현하거나 적합한 유형을 활용할 수 있는 추가 기능을 구현할 수 있습니다.

객체의 유연한 설계를 위해서는 정의와 구현이 분리되어야합니다. 즉, 객체가 OCP 원칙을 지키기 위해서는 정의와 구현을 분리해야합니다.

**Comment by Lim-YongKwan** [comment]
프로토콜이란 특정 역할을 하기 위한 메서드, 프로퍼티, 기타 요구사항 등의 청사진을 정의한다.

그러므로, 프로토콜은 정의를 하고 제시를 할 뿐 스스로 기능을 구현하지는 않는다.



프로토콜 기본 사용 방법

```
protocol 프로토콜_이름{
	프로토콜_정의
}
```

구조체, 클래스, 열거형 등에서 프로토콜 사용 방법

```
struct AnyStruct: AProtocol, AnotherProtocol {
	//구조체 정의
}
```

**Comment by hongssup** [comment]
https://hongssup.tistory.com/489
