### ISSUE TITLE
[6주차] Protocol Oriented Programming과 Object Oriented Programming의 차이점을 설명하시오.

### ISSUE THREAD

**Issue by kangddong** [LetsSwifty/iOS_Interview#7]

**Comment by obtusa07** [comment]
# Inheritance vs. Composition (상속 혹은 구성)

OOP는 한 클래스가 부모 클래스로부터 속성과 동작을 상속할 수 있는 **상속**을 사용
POP는 한 유형이 여러 프로토콜을 준수하고 프로토콜 확장을 사용하여 메서드와 속성의 기본 구현을 제공할 수 있는 **구성**을 사용

# Static Dispatch vs. Dynamic Dispatch (정적 디스패치 혹은 동적 디스패치)
OOP는 정적 디스패치를 사용하며, 여기서 호출할 메서드는 객체의 유형에 따라 컴파일 타임에 결정 
POP는 동적 디스패치를 사용하며, 호출할 메서드는 객체의 실제 유형에 따라 런타임에 결정
스위프트의 경우 컴파일 무조건 Dynamic Dispatch만을 이용해야 하는 것은 아니다. (언어의 특성이 그렇다는 것)

# Type vs. Protocol 
OOP는 클래스 및 개체를 만드는 데 초점을 맞추고 
POP는 프로토콜을 만들고 기본 동작으로 확장하는 데 초점을 맞춘다

# Strong vs. Weak Typing
OOP는 일반적으로 강력한 타이핑과 관련이 있으며, 여기서 컴파일 시 개체의 유형이 고정된다.
POP는 종종 약한 타이핑과 관련이 있는데, 여기서 객체의 유형은 런타임에 결정되며 준수하는 프로토콜에 따라 변경될 수 있다.

전반적으로, POP와 OOP의 주요 차이점은 그들이 작동하는 추상화의 수준이다. OOP는 특정 클래스 및 개체를 만드는 데 초점을 맞추고 POP는 재사용 가능한 프로토콜을 만들고 기본 동작으로 확장하는 데 초점을 맞춘다.

**Comment by kangddong** [comment]
Protocol Oriented Programming은 프로토콜 중심 프로그래밍, Object Oriented Programming은 객체 중심 프로그래밍입니다. POP는 프로토콜 확장을 통하여 수평 구조로 타입을 확장하고, OOP는 슈퍼클래스의 상속을 통하여 수직 구조로 타입을 확장하는 방식으로 다형성을 구현 합니다.

Keyword Polymorphism(다형성)
OOP -> IS-A 
* 단점:
    *  슈퍼클래스에 너무 종속적이다.
    * Value Type을 사용할 수 없다. (Swift에서는 참조 타입이 반드시 필요한 상황이 아니라면, 가급적 값 타입을 사용하라고 공식적으로 가이드하고 있다.)

POP -> Has-A
편리한 점: OOP의 불편한 점을 해결해준다.

구현부 입장에서 알아야 할 것은 '프로토콜이 요구하는 변수와 함수' 뿐이다.
슈퍼클래스와 서브클래스의 의존적인 관계와 다르게, 프로토콜 기반의 구조에서는 프로토콜에 정의된 부분을 구현해놓으면 된다. 
슈퍼클래스를 상속받는 서브클래스들과 달리, 같은 프로토콜을 따르는(conforms to) 사이에도 끈끈하게 엮여있는 부분이 없으므로 각각이 독립적이며 그래서 안전하다

상속 구조에서는 오직 하나의 슈퍼클래스만 가질 수 있다. 그러나 프로토콜의 경우에는 다수의 프로토콜을 따르는 것이 가능하다. 또한 물려받아 재사용하는 개념이 아니기 때문에, 다중 상속의 문제점으로 언급되는 죽음의 다이아몬드 이슈에서도 자유롭다.

**Comment by Lim-YongKwan** [comment]
스위프트는 프로토콜 지향 언어입니다.
스위프트의 대부분은 구조체로 기본 타입이 구현되어 있으며 구조체는 클래스와 달리 상속이 불가능합니다. 이와 같이 상속도 되지 않는 구조체가 다양한 공통 기능을 가질 수 있는 이유는 Protocol과 Extension에 있다.

OOP의 단점
1. SuperClass에 종속적이다.
- Subclassing을 하여 사용하기 위해서는 superclass의 코드를 알고 있어야 한다.
- 서브클래스는 불필요한 변수화 함수를 상솓받을 수 밖에 없다.

2. Value Type을 사용할 수 없다.
-  참조 타입은 참조 추적에 비용이 많이 발생한다. 하지만 상속을 사용하기 위해서는, 값 타입으로 정의해도 무방한 모델들을 굳이 참조 타입으로 정의해야 한다.

POP의 장점
1. SuperClass에 독립적
2. 값 타입 사용 가능
3. 가볍고 안전하다
  - 상속은 참조 타입이라 참조 추적을 위한 비용으로 인하여 속도측면에서 저하가 되는 반면 POP를 통해 값타입에서 상속과 같은 역할 가능.
4. 기능의 모듈화 가능
5. 불필요한 API를 제외하고 정의한 API만 가져올 수 있음
6. 수직 구조 확장이 아닌 수평 구조의 기능 확장

**Comment by hongssup** [comment]
https://hongssup.tistory.com/495
