### ISSUE TITLE
[6주차] Hashable이 무엇이고, Equatable을 왜 상속해야 하는지 설명하시오.

### ISSUE THREAD

**Issue by kangddong** [LetsSwifty/iOS_Interview#8]

**Comment by obtusa07** [comment]
# Hashable이란
스위프트에서 Hashable은 프로토콜의 일종이다. 이것을 선언하면 해당 타입의 Set의 요소 타입이나 Dictionary의 Key 타입이 될 수 있다. 해당 프로토콜을 준수하려면 객체의 해시 값을 만드는 데 사용되는 hashValue 속성을 구현해야 한다.

# Equatable이란
Equatable 프로토콜은 동일한 유형의 두 개체를 비교하기 위한 == 연산자를 정의한다. 
Equatable 프로토콜을 사용하려면 유형이 두 개체가 동일한지 여부를 결정하는 == 연산자를 구현해야 한다.

## 왜 Equatable을 상속 받아야 하지?
어떤 타입이 Set의 요소 타입이나 딕셔너리의 key 타입이 되려면 위의 두 프로토콜을 준수해야 한다. Set과 딕셔너리 컬렉션이 요소의 동일성과 고유성을 검증하기 위해 Hashable, Equatable 프로토콜을 준수하기 때문이다.

**Comment by kangddong** [comment]
정의
Hashable은 "정수 hash 값을 제공하는 타입"으로 정의된 프로토콜입니다.
hash란, 해시 함수에 의해 얻어지는 값으로 해시값, 해시코드, 해시 체크섬으로도 불립니다.
해시 함수 - 임의의 길이의 데이터를 고정된 길이의 데이터로 매핑하는 함수
hashValue - 어떠한 데이터를 Hash 함수에 넣게 되면 반환해주는 값
HashTable에서 hash값을 찾기 위해선 key가 필요하고 이 key는 식별할 수 있도록 unique 해야 합니다.



정의
Equatable은 값이 동일한 지 어떤지를 비교 할 수 있는 타입인 프로토콜입니다.
이 프로토콜을 준수하는 타입은 == 혹은 != 사용하여 동등성을 비교할 수 있습니다.
왜 Hashable은 Equatable을 상속해야할까?
hashValue는 고유값이어야 하므로 고유값인지 식별해 줄 수 있는 "==" 함수가 필요합니다.
그 함수는 Equatable 프로토콜 안에 들어있습니다.
따라서 Hashable이 Equatable을 상속해야 합니다.

**Comment by Lim-YongKwan** [comment]
# **Hashable**

정수 해쉬 값을 제공하기 위해서 Hasher를 통해 해쉬화 될 수 있는 타입, 프로토콜

반드시 하나만 존재해야하는 딕셔너리의 키 값이나 중복된 값은 허용하지 않는 자료구조인 세트에 들어가는 값을 정수 값으로 변환하여 각각의 인스턴스를 정수 값을 통해 접근할 수 있도록 해준다.

Set 또는 Dictionary의 Key로 hashable을 준수하는 모든 타입을 사용할 수 있음. 표준 라이브러리의 왠만한 기본 타입은 기본적으로 hashable임 옵셔널이나 배열 range의 경우에는 자동으로 hashable이 될 수 있는데 when their type arguments implement the same 일때 ??

Equatable를 상속하므로 반드시 둘의 조건 모두 충족해야함

swift 4.1 이후에는 사용자 정의 타입에서 채택만 하면 자동으로 hashValue를 만들어줌. (모든 저장 프로퍼티가 Hahsable한 값일때 ) Set에도 들어갈 수 있고 Dictionary Key로도 들어갈 수 있다.


## **Equatable**

값이 같은지 비교할 수 있는 타입 , 프로토콜

Equatable를 따르는 타입은 ==operator 나 != operator를 통해서 인스턴스 값의 동일성을 비교할 수 있음

시퀀스나 콜렉션의 경우 엘리멘트들이 이 프로토콜을 따르면 좀 더 쉽게 사용할 수 있다.

엘리멘트들이 동일성을 결정하는 클로저를 제공하는 것이 아니라 Equatable를 따르면 array 가 특정 값을 가지고 있는지 확인하기 위해서 contains(_: )를 사용할 수 있음

## **Hashable이 Equatable를 상속해야하는 이유**

Hashable 프로토콜을 준수하는 모든 인스턴스는 hashValue라는 정수형 프로퍼티를 갖고 있으며 이 값은 각각의 인스턴스를 식별하는 값이 된다. 즉 인스턴스끼리 같은지 다른지 비교해야하므로 Equatable 상속이 필요함

이전에 처리 방식을 보면 Hashable 조건을 따르기 위해서 == 오퍼레이터와 hash(into:) 함수를 씀

**Comment by hongssup** [comment]
https://hongssup.tistory.com/493
