### ISSUE TITLE
[6주차] mutating 키워드에 대해 설명하시오.

### ISSUE THREAD

**Issue by kangddong** [LetsSwifty/iOS_Interview#9]
2023/01/04 진도 상황에 따라 7주차로 변경될 수 있는 분량

**Comment by obtusa07** [comment]
class, enum, struct와 같은 타입에서 인스턴스 메서드를 생성하고 사용하고자 하는 경우 class는 내부 프로퍼티를 조작하는 것에 문제가 없다.

하지만 enum, struct는 value 타입이기에 수정이 접근하여 수정하는 것이 불가능한데 이 때, 메서드의 앞에 mutating 키워드를 func 앞에 붙여 값을 변경할 수 있게 한다는 것을 명시한다.

**Comment by kangddong** [comment]
클래스는 reference 타입이고 struct와 enum 는 value type입니다.
값 타입의 속성은 기본적으로 인스턴스 메서드 내에서 수정할 수 없습니다. 만약 수정해야하는 경우 mutating을 붙여주면 됩니다.

mutating을 선언한 메서드는 메서드 내에서 프로퍼티를 변경할 수 있고, 메서드가 종료될 때 변경한 모든 내용을 원래 struct에 다시 기록합니다.
또한 메서드는 self property에 새 인스턴스를 할당할 수도 있습니다.
mutating 키워드는 해당 메서드가 호출된다면 실제 복사를 해야한다고 알려주는 역할입니다.

mutating 키워드를 사용한 메서드에서 프로퍼티를 변경하면 변경된 새로운 구조체를 인스턴스에 할당하게 된다.

**Comment by Lim-YongKwan** [comment]
mutating
mutating은 객체를 바꾸는 함수임을 알리는 키워드이다.
구조체 내부 함수에서 변수를 바꾸려고 할 때 mutating 키워드가 없으면 'self' ~~ 에러가 발생한다.

값 타입은 스택 메모리에 저장이 된다. 그렇기에 구조체는 전달될 때마다 참조가 아니라 매번 복사되어 전달되기 때문에 굉장히 비효율적이라고 할 수 있다.
Swift에서는 이와 같은 부분을 효율적으로 만들기 위하여 값이 변경되었을 때 복사를 하도록 만들어 졌다.
이와 같이 구조체의 값을 변경하는 함수에서 알려주는 키워드가 바로 mutating이다.

**Comment by hongssup** [comment]
https://hongssup.tistory.com/494
